# Site settings
title: *folio
name: Tessa Blanken
email: tessablanken@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tessa Blanken | PhD Student | Insomnia · Depression · Network Models · Complex Systems
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: tfblanken
github_username:  tfblanken

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


plugins:
  - jekyll-feed
  - jekyll-paginate